# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Inicio
    url: "#inicio"
    weight: 10
  - name: Conócenos
    url: conocenos
    weight: 20
  #- name: Patrocinadores
  # url: noticias
  # weight: 20
  - name: Equipo
    url: equipo
    weight: 30
  - name: Organigrama
    url: organigrama
    weight: 35
  # - name: Eventos
  #   url: eventos
  #  weight: 40
  # - name: Publicaciones
  #   url: publicaciones
  #   weight: 50
  - name: Contacto
    url: contacto
    weight: 60
